language: java
env:
  matrix:
  - IDEA_VERSION=IC-15.0.4
  - IDEA_VERSION=LATEST-EAP-SNAPSHOT
  global:
  - secure: yCs49nxibY6fxhgY31FihYBnxULR2pvSgJsEU8fmkRN9Y82WfQ+Tvor19edl3+aQhXEO8h+N0rddAEuzlPXvOKiedWr8UOrtf55j2rsM42E82199ooju0eHIFuhWefGsG9we9sexoxu43zckRu/N9aYA4aQ4TA1U1QWCJRBiSdDJewg0j3kzADkqBqwxlJiVoLabKb/qjgyRkUMN04vggIm8uL0knepr5qhepkTtphOIOmOUkdKgHzIMx65stKGqc2u0hGwBUW3TA5mze/5DFtHqMtLBU1v37Qc0G8Rx28CaFbFeW+K7FhIMjYAw7fiHRwMK7Xm04hoAcfxigDI2PmG5Nq9kLBXtkjC4sp6jP5HA6We6ZYR90xUlqhAMyng/FTMGg7pfAzudY1LsYwdSc2ntJ3T8Nak5J2No8Z8hwzGDa7x+R969fis74+7jB1fs5Xt1+2uwnkgG3+dvKYaN5or3FlDWdk1Jpsb+pLZJfX8mP7Rm7Cu2nlQIryWsbCsOgGD27cPh4ouhTd+JkOgJrlNXZN+yHMv0JXIvOJNVyGuX1WjmoloPzZXdUb3Xo/RjAvmk863cftc28FczpodTQ1KqXav/VS1vftNwo0hAYDuCOysIHn/5CZu0s6c9p5vf1CbutHrKnfHda8yQ0qlXs22xOQMot60hR+vQuqNf0RE=
jdk:
- oraclejdk7
script:
- ./gradlew test -PideaVersion=$IDEA_VERSION
notifications:
  email: false
cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle
after_success:
- .travis/after_success.sh
